FROM resin/%%RESIN_MACHINE_NAME%%-node:6-slim

WORKDIR /usr/src/app

COPY package.json package.json

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache clean && rm -rf /tmp/*

COPY . ./

# server.js will run when container starts up on the device
CMD ["npm", "start"]
