version: '2'
services:
  frontend:
    build: ./frontend
    expose:
      - "80"
  datadog:
    build: ./datadog
    privileged: true
    restart: always
    pid: "host"
    network_mode: "host"
    labels:
      io.resin.features.dbus: '1'
      io.resin.features.balena-socket: '1'
